### ISSUE TITLE
dns_id应该填什么？

### ISSUE THREAD

**Issue by whtiehack** [EtherDream/jsproxy#1]
执行 ./build.sh 时候申请证书一直不成功。

**Comment by EtherDream** [comment]
参考：https://github.com/Neilpang/acme.sh/tree/master/dnsapi
比如阿里云就是：
```
DNS_ID=dns_ali
export Ali_Key="sdfsdfsdfljlbjkljlkjsdfoiwje"
export Ali_Secret="jlsdflanljkljlfdsaklkjflsa"
```

**Comment by whtiehack** [comment]
这一步好了。 感谢回答。

**Comment by lininn** [comment]
不对 



./dnsconf: line 1: $'\377\376DNS_ID=dns_cf\r': command not found
[Thu Mar  7 22:01:38 EST 2019] '-d' is not a valid domain for parameter '-d'
[Thu Mar  7 22:01:38 EST 2019] '-d' is not a valid domain for parameter '-d'
[Thu Mar  7 22:01:38 EST 2019] '--key-file' is not a valid domain for parameter '-d'
[Thu Mar  7 22:01:38 EST 2019] '--ecc' is not a valid domain for parameter '-d'

**Comment by whtiehack** [comment]
前提是 先执行 `./server/setup.sh` 安装依赖，然后再仔细看一下配置，我是没有问题的。
