### ISSUE TITLE
setup-ipset.sh无法运行

### ISSUE THREAD

**Issue by breakwa2333** [EtherDream/jsproxy#105]
Ubuntu不自带ipset，需要自己安装，希望能在readme中提及，谢谢！
![image](https://user-images.githubusercontent.com/48397771/61017468-e35e3e80-a3c5-11e9-96d2-131f41d6fc4d.png)

**Comment by wi1dcard** [comment]
其实不用 ipset 直接 iptables 也一样。

**Comment by EtherDream** [comment]
> 其实不用 ipset 直接 iptables 也一样，没几个地址。

这里可以做个兼容。之前 openvz 还用不了 ipset。。。

**Comment by EtherDream** [comment]
之前有考虑用 ipset 做 IP 黑名单，禁止访问某些网站。不过现在打算在 nginx 里实现。

**Comment by wi1dcard** [comment]
我认为域名黑名单更好些，相比之下更容易控制某一批站点，IP 黑名单虽然更精确，但是很多场景下需要大量精力才能维护完善。
