### ISSUE TITLE
Cloudflare Worker 版无法使用 Startpage 搜索

### ISSUE THREAD

**Issue by xanadus0** [EtherDream/jsproxy#106]
在 `Startpage.com` 输入关键词搜索后，仍显示首页。

似乎是因为 Startpage 默认使用 POST 请求，并不像 Google 和 DuckDuckGo 一样默认使用 GET 请求。

**Comment by EtherDream** [comment]
是有问题，我修复下

**Comment by EtherDream** [comment]
https://a.007.workers.dev/-----https://startpage.com/  可以搜索了

**Comment by xanadus0** [comment]
感谢开发者更新。另外我在更新后遇到了新问题。

尝试搜索，无论什么关键词都显示如下信息：
![Screenshot](https://user-images.githubusercontent.com/35560692/61094182-8bd0d900-a480-11e9-8294-3df4fad235c7.PNG)

而切换到 Images 或 Videos 选项卡后，结果正常：
![Screenshot1](https://user-images.githubusercontent.com/35560692/61094215-c3d81c00-a480-11e9-8df1-0f442819d559.PNG)

※ 使用您提供的示例 `https://a.007.workers.dev/-----https://startpage.com/` 也是同样结果。

我本地的软件版本如下：
Microsoft Windows 8.1 x64
Google Chrome 版本 75.0.3770.100（正式版本） （64 位） ※ 已禁用所有插件和已清空缓存

**Comment by EtherDream** [comment]
我这里能搜出结果。。。

<img width="1232" alt="" src="https://user-images.githubusercontent.com/1072787/61095525-57f8b200-a486-11e9-9d1e-eed1463a92d7.png">

**Comment by xanadus0** [comment]
请问您在测试时是否在本地配置了代理，我在测试时发现，在直连时会出现我之前提到的错误，而使用代理后结果正常。

**Comment by EtherDream** [comment]
> 请问您在测试时是否在本地配置了代理，我在测试时发现，在直连时会出现我之前提到的错误，而使用代理后结果正常。

好像有这个现象。我看看哪个资源加载出问题了

**Comment by xanadus0** [comment]
解决了，不是软件的问题，是浏览器优先使用 IPv6 导致的。😂
