### ISSUE TITLE
Can't sign in google.

### ISSUE THREAD

**Issue by sunyuan3** [EtherDream/jsproxy#108]
https://jsproxy.gq/-----https://www.google.com/
![20190712153654](https://user-images.githubusercontent.com/10508990/61110918-eedf6180-a4ba-11e9-9c83-1d15d9f5ab02.jpg)

**Comment by EtherDream** [comment]
脚本有问题，暂时还不支持。

**Comment by chen19870509** [comment]
其实不建议支持
因为一旦发布不当言论，这个是违法的
就简单的代理下google，查查资料可以了

**Comment by EtherDream** [comment]
以后会支持登陆，当然演示服务也会加上禁止登陆的功能。

**Comment by ourlove5** [comment]
希望尽快支持pinterest.com 也无法登录

**Comment by uicba** [comment]
@EtherDream 快点删除这个issue，楼主没给手机号打马赛克。

**Comment by uicba** [comment]
@EtherDream issue是公开的，你close没有用。
