### ISSUE TITLE
访问google.com问题，访问页面其他的图标站点都可以

### ISSUE THREAD

**Issue by ckgmg** [EtherDream/jsproxy#113]
访问google.com问题，访问页面其他的图标站点都可以，线路使用“当前站点“
![image](https://user-images.githubusercontent.com/49260651/61433884-1032c880-a967-11e9-95f0-072d4d0c701e.png)

**Comment by ckgmg** [comment]
vps是双IP的，

**Comment by ckgmg** [comment]
验证后这样的
![image](https://user-images.githubusercontent.com/49260651/61436757-0c567480-a96e-11e9-9a30-fced23bf3cdc.png)

**Comment by ckgmg** [comment]
这是一个BUG，双IP的网络就出现以上的错误，单IP就正常，

**Comment by EtherDream** [comment]
和 IP 没关系，是代理脚本的 bug。现在 google recaptcha 没法在代理页面里执行。

**Comment by ckgmg** [comment]
请问下，页面下当前站点，是不是走的是自己的IP，




------------------ 原始邮件 ------------------
发件人: "EtherDream"<notifications@github.com>; 
发送时间: 2019年7月19日(星期五) 上午10:12
收件人: "EtherDream/jsproxy"<jsproxy@noreply.github.com>; 
抄送: "蒙祖桃"<37930312@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [EtherDream/jsproxy] 访问google.com问题，访问页面其他的图标站点都可以 (#113)




和 IP 没关系，是代理脚本的 bug。现在 google recaptcha 没法在代理页面里执行。

**Comment by EtherDream** [comment]
> 请问下，页面下当前站点，是不是走的是自己的IP，
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "EtherDream"<notifications@github.com>; 发送时间: 2019年7月19日(星期五) 上午10:12 收件人: "EtherDream/jsproxy"<jsproxy@noreply.github.com>; 抄送: "蒙祖桃"<37930312@qq.com>; "State change"<state_change@noreply.github.com>; 主题: Re: [EtherDream/jsproxy] 访问google.com问题，访问页面其他的图标站点都可以 (#113) 和 IP 没关系，是代理脚本的 bug。现在 google recaptcha 没法在代理页面里执行。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

走代理服务器的 IP。
