### ISSUE TITLE
推特 Error 1101

### ISSUE THREAD

**Issue by Puled** [EtherDream/jsproxy#118]
我按照详细的教程自己开了一个workers，可是打不开twitter，显示错误1101.
对于我这种电脑纯小白而言，完全不知道该怎么做。

请帮帮我，万分感谢！
<img width="888" alt="1" src="https://user-images.githubusercontent.com/30209777/61687437-fe7d6680-ad54-11e9-87a9-4b075ef96a2f.PNG">

**Comment by EtherDream** [comment]
我这里能打开你的地址，可能是 cloudflare 的问题吧

**Comment by sharwinmail** [comment]
这个代理能用,但有些代理起来会有些小问题,我目前改用一家带有部分免费公益节点代理软件了,看看普通视频和对网速要求不是很高用免费节点就行了,希望能长久,有需要可以试试 http://t.cn/AilHEmkm

**Comment by sharwinmail** [comment]
这个代理大部分功都能用,但有些代理起来会有些小问题,我目前改用一家带有部分免费公益节点代理软件了,看看普通视频和对网速要求不是很高用免费节点就行了,希望能长久,有需要可以试试 http://t.cn/AijMBH6x

**Comment by kinglyl** [comment]
出现了vpn贩子
