### ISSUE TITLE
为什么在xxx.workers.dev中可以，但在xxx.github.io中会报404?

### ISSUE THREAD

**Issue by tamada007** [EtherDream/jsproxy#119]
我通过xxx.workers.dev的方式，选择“当前节点”可以访问.
通过xxx.github.io/jsproxy的方式，选择“当前节点”会报404,用"演示服务"可以访问。
都是按教程做的。
有什么办法吗？

**Comment by EtherDream** [comment]
“当前节点”表示后端服务器使用当前域名，xxx.github.io 域名当然没有后端服务，所以会报错。需要在 conf.js 里配置一个新节点，把 xxx.workers.dev 加进去。

**Comment by tamada007** [comment]
大神威武
