### ISSUE TITLE
部署成功，发现nginx加载配置文件不对，如何修改nginx -c的文件？

### ISSUE THREAD

**Issue by lininn** [EtherDream/jsproxy#12]

**Comment by EtherDream** [comment]
你是怎么启动的？

**Comment by lininn** [comment]
Build默认启动的，发现nginx在usr/local/openresty/nginx目录下，加载的conf也是这个目录，这个目录的nginx.conf文件不正确，使用-c命令不生效


发件人: EtherDream
发送时间: 2019年3月11日 16:18
收件人: EtherDream/jsproxy
抄送: lininn; Author
主题: Re: [EtherDream/jsproxy] 部署成功，发现nginx加载配置文件不对，如何修改nginx -c的文件？ (#12)

你是怎么启动的？

**Comment by lininn** [comment]
你是启动了守护进程？关闭nginx重新配置-c，请问如何操作呢？

**Comment by lininn** [comment]
/usr/local/openresty/nginx/sbin/nginx -t
nginx: the configuration file /usr/local/openresty/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test is successful


这个无法修改到jsproxy目录去。。。该如何操作？

**Comment by EtherDream** [comment]
用 ./server/run.sh 启动也有这个问题吗？

**Comment by lininn** [comment]
部署到根目录，文件夹为jsproxy，然后运行./server/run.sh ,发现启动的/usr/local/openresty/nginx/sbin/nginx 是这个，然后配置文件为这个目录下的conf,切无法用-c修改，绝望了

**Comment by EtherDream** [comment]
> 部署到根目录，文件夹为jsproxy，然后运行./server/run.sh ,发现启动的/usr/local/openresty/nginx/sbin/nginx 是这个，然后配置文件为这个目录下的conf,切无法用-c修改，绝望了

配置文件本来就是这个目录下的 conf 啊，你是想还要和其他的 nginx 配置共存吗

**Comment by lininn** [comment]
我以为配置文件为 /jsproxy/server/nginx.conf这个文件，如果为/usr/local/openresty这个文件的，那么安装后无法访问

**Comment by EtherDream** [comment]
试试最新版本，所有文件都换成绝对路径
