### ISSUE TITLE
在 cfworker 上部署出现问题

### ISSUE THREAD

**Issue by marsvet** [EtherDream/jsproxy#128]
点击 Save and Deploy 后提示
workers.api.error.not_found (Code: 10007)

请问这是什么问题呢

**Comment by Jeff-Tian** [comment]
+1

**Comment by Jeff-Tian** [comment]
我碰到同样的问题，应该是 cloudflare 的BUG。但不影响，虽然有报错，但实际上已经成功保存和部署了。访问网站没问题，关闭 editor，重新从 list 进入，然后再点保存和部署，就不会报错了。

**Comment by marsvet** [comment]
哈哈确实，重新进入就好了。

谢谢大佬

**Comment by ericheroster** [comment]
我也出现了这个问题

重新进入worker list 还是空的呀
