### ISSUE TITLE
https://gamedun.github.io

### ISSUE THREAD

**Issue by GameDun** [EtherDream/jsproxy#135]
https://gamedun.github.io

Host:   185.199.110.153 gamedun.github.io

**Comment by Freddd13** [comment]
请问这个怎么搭建出github.io的？ 我的workers cloudflare访问google卡在人机身份认证，速度也很慢

**Comment by uicba** [comment]
@GameDun 怎么把jsproxy搭在GitHub Pages上？

**Comment by Jackson-Chen2007** [comment]
**我也想问怎么搭在github pages(顺表在教下后端搭建呗)**

**Comment by kinglyl** [comment]
Fork -> 在gh-pages里面建一个index.html，不需要写东西 -> 在repo的设置里面 GitHub Pages 选项里选择gh-pages分支 -> 建好了以后删掉index.html

**Comment by goxofy** [comment]
就是普通的ghpages呀

**Comment by Hew007** [comment]
挂了

**Comment by v2cn** [comment]
嗯，今天访问不到了。

**Comment by sam-netizen** [comment]
https://zjcqoo.github.io/
都访问不了

**Comment by sam-netizen** [comment]
@GameDun
正常可以访问了，谢谢。

**Comment by FE-honour** [comment]
这个项目真的是太棒了

**Comment by bhz6344** [comment]
感谢慷慨的作者 @EtherDream，其实我们Fork之后用的仍然是作者的服务器节点

**Comment by KL450** [comment]
https://zjcqoo.github.io/

訪問不到了？

**Comment by KL450** [comment]
> https://gamedun.github.io
> 
> Host: 185.199.110.153 gamedun.github.io

@GameDun 兄, 昨天30 Oct.開始不能用了？

**Comment by KL450** [comment]
LOL

**Comment by 51freedom** [comment]
不行了

**Comment by sam-netizen** [comment]
@GameDun 
挂掉了？

**Comment by lvfeijun** [comment]
https://zjcqoo.github.io/都访问不了
😂
求新代理~

**Comment by lvfeijun** [comment]
> https://gamedun.github.io
> 
> 主持人：185.199.110.153 gamedun.github.io

大哥~求新代理

**Comment by GameDun** [comment]
作者把服务器关了

**Comment by sam-netizen** [comment]
……

**Comment by popsee** [comment]
> Fork -> 在gh-pages里面建一个index.html，不需要写东西 -> 在repo的设置里面 GitHub Pages 选项里选择gh-pages分支 -> 建好了以后删掉index.html

原来如此，精彩的解释！
