### ISSUE TITLE
只有连接vpn才能登陆这个网站

### ISSUE THREAD

**Issue by lostever** [EtherDream/jsproxy#137]
又一个被墙的神器，
![Screenshot_2019-08-14-11-08-01](https://user-images.githubusercontent.com/44220239/62991969-4b4feb00-be84-11e9-8d15-fcd2c7ef088c.png)

**Comment by lostever** [comment]
有跟我一样情况的朋友吗？
怎么处理的？

**Comment by GameDun** [comment]
用我的https://gamedun.github.io

**Comment by kinglyl** [comment]
改了就是为了不要大范围的。。。

**Comment by EtherDream** [comment]
好像第一次VPN之后就不需要了23333

**Comment by lostever** [comment]
> 用我的https://gamedun.github.io

谢了哈老哥

**Comment by uicba** [comment]
> 用我的https://gamedun.github.io

怎么把jsproxy搭在GitHub Pages上？

**Comment by KL450** [comment]
> 用我的https://gamedun.github.io

Ching, 昨天開始不能用了？

**Comment by yanglr** [comment]
@GameDun Now, it does not work, display "load fail".
