### ISSUE TITLE
cfworker前端脚本错误问题

### ISSUE THREAD

**Issue by kinglyl** [EtherDream/jsproxy#138]
用`cfworker`搭建了一个，能用，我把静态网页放在了`gh-pages`上，在`conf.js`里新建了一个，填的是`cfworker`的地址，每次一开始打开静态网页时，不管点哪里，都会提示前端脚本错误，在切换列表里换一下就ok了，不知道是什么原因。

**Comment by EtherDream** [comment]
默认节点设置为 cfworker 的地址，不要设为当前站点。

**Comment by kinglyl** [comment]
> 默认节点设置为 cfworker 的地址，不要设为当前站点。

默认节点就是cfworker的地址

**Comment by kinglyl** [comment]
进入静态网页以后，点切换列表，换成其他的节点再换回来（或者不换）就正常了。

**Comment by kinglyl** [comment]
控制台提示 `nknown node` , 但是我配置没毛病。。。

**Comment by kinglyl** [comment]
仔细研究发现是默认节点里少打了个字母。。。
