### ISSUE TITLE
Docker版jsproxy

### ISSUE THREAD

**Issue by Fuleen** [EtherDream/jsproxy#143]
感谢作者提供这么棒的应用，根据i.sh写了个Dockerfile，另一个小伙伴的Dockerfile也很棒，不过用的centos，有点大，我换了个alpine。

[https://github.com/Fuleen/docker_jsproxy](url)

**Comment by Puled** [comment]
hey，作者八月份怎么没消息了，我觉得咱们还是低调一些吧，这项目到6000多个星星了，小心被盯上。

**Comment by Fuleen** [comment]
> 
> 
> hey，作者八月份怎么没消息了，我觉得咱们还是低调一些吧，这项目到6000多个星星了，小心被盯上。

OK,那我删掉吧
