### ISSUE TITLE
部署失败build.sh报错

### ISSUE THREAD

**Issue by lonelykid** [EtherDream/jsproxy#15]
[Mon Mar 18 15:47:40 UTC 2019] invalid domain
[Mon Mar 18 15:47:40 UTC 2019] Error add txt for domain:_acme-challenge.xxx.xxx
[Mon Mar 18 15:47:40 UTC 2019] Please add '--debug' or '--log' to check more details.
[Mon Mar 18 15:47:40 UTC 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

ERROR in main.js from Terser
Invalid regular expression: /(?<=;\s*domain=)[^;]+/: Invalid group [main.js:1243,26]

用的dnspod.com

**Comment by EtherDream** [comment]
用的是最新版的 webpack 吗？老版本的识别不了这个正则语法。。。

**Comment by lonelykid** [comment]
是最新版啊，webpack@4.29.6， webpack-cli@3.3.0，./server/setup.sh 安装的。CentOS-7
这是两个error

**Comment by EtherDream** [comment]
最新版本已删除这个正则，老版本的 webpack 也不会报这个错了。
