### ISSUE TITLE
google账号无法登入

### ISSUE THREAD

**Issue by h5mcbox** [EtherDream/jsproxy#159]
已经影响y2b评论了

**Comment by h5mcbox** [comment]
登入界面输完密码按不了登入

**Comment by uicba** [comment]
https://github.com/EtherDream/jsproxy/issues/134#issuecomment-522390134
不建议在网页代理登录账户

**Comment by uicba** [comment]
https://github.com/EtherDream/jsproxy/issues/134#issuecomment-522390134
为了安全，不建议在网页代理登录账户。

**Comment by h5mcbox** [comment]
但是ss找不到啊
