### ISSUE TITLE
`CSDN`重定向bug

### ISSUE THREAD

**Issue by ddzy** [EtherDream/jsproxy#16]
## Issue Type
bug
## Current Feature
打开任意的csdn博客, 会重定向到首页:
![hub_issue_1](https://user-images.githubusercontent.com/33921398/54601390-e7163000-4a79-11e9-96e8-b93c62fa1051.gif)

**Comment by EtherDream** [comment]
是的，这个版本有好多的 BUG。。。过段时间我更新一个新版本的，修复了很多问题

**Comment by ddzy** [comment]
> 是的，这个版本有好多的 BUG。。。过段时间我更新一个新版本的，修复了很多问题

坐等

**Comment by EtherDream** [comment]
最新版本已修复这个问题
