### ISSUE TITLE
jsproxy好像被墙了😂😂😂

### ISSUE THREAD

**Issue by pzb568** [EtherDream/jsproxy#169]
地址<https://pzb568.github.io/jsproxy>

**Comment by sam-netizen** [comment]
https://zjcqoo.github.io/
被墙了…

**Comment by sam-netizen** [comment]
@EtherDream
等你来救，嘻嘻。

**Comment by xy9527** [comment]
期待大佬出手

**Comment by lvfeijun** [comment]
期待大佬出手

**Comment by kinglyl** [comment]
这个issue关了吧，zjcqoo.github.io 被墙了不影响cfworker也不影响项目本身，你们要用的话自己搭。

**Comment by sam-netizen** [comment]
@GameDun
正常可以访问了，谢谢。
