### ISSUE TITLE
静态资源url小问题。。

### ISSUE THREAD

**Issue by Niksend** [EtherDream/jsproxy#177]
目前使用cfworkers部署，想自行修改配置文件并进行二次开发之类的。。（指index.js里的ASSETURL）
不过发现好像莫得项目有这个。。
不知道dalao能否指点一下。。谢谢啦

**Comment by ainuoyan** [comment]
修改静态文件

**Comment by Niksend** [comment]
> 修改静态文件

具体地址在哪里方便说一下么。。。谢谢啦

**Comment by Niksend** [comment]
之前用了是gh-pages分支，修改worker的asseturl后会报错。。
