### ISSUE TITLE
“/”应用程序中的服务器错误。

### ISSUE THREAD

**Issue by Neteraxe** [EtherDream/jsproxy#180]
执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。
--

重定向后出现这个错误

**Comment by Neteraxe** [comment]
执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。
--

**Comment by EtherDream** [comment]
？

**Comment by Neteraxe** [comment]
谢谢开发者，我的问题太多了还是算了先不问了

在 2019-11-01 11:22:29，"EtherDream" <notifications@github.com> 写道：


？
