### ISSUE TITLE
太好用的软件了。但如何修改：将“当前站点”那个框，内容全部删除？

### ISSUE THREAD

**Issue by becapital** [EtherDream/jsproxy#188]
太好用的软件了。但如何修改：将“当前站点”那个框，内容全部删除？

**Comment by h5mcbox** [comment]
gh-pages分支里conf.js删掉下面部分（不要删了nodemap的大括号）
'demo-hk': {
      label: '演示服务-香港节点',
      lines: {
        // 主机:权重
        'node-aliyun-hk-1.etherdream.com:8443': 1,
        'node-aliyun-hk-2.etherdream.com:8443': 2,
      }
    },
    'demo-sg': {
      label: '演示服务-新加坡节点',
      lines: {
        'node-aliyun-sg.etherdream.com:8443': 1,
      },
    },
    'mysite': {
      label: '当前站点',
      lines: {
        [location.host]: 1,q
      }

**Comment by becapital** [comment]
谢谢

**Comment by h5mcbox** [comment]
关了issue吧
