### ISSUE TITLE
为什么Pixiv的图片无法显示，cfworkers版

### ISSUE THREAD

**Issue by gaowanliang** [EtherDream/jsproxy#192]
按照教程走了一遍，但是无法显示，是403问题

**Comment by k79e** [comment]
应该是refer没传达 他们是防盗链的.

**Comment by Puled** [comment]
`https://www.boxpaper.club/PixivUMP ` Pixiv代理
`https://www.veryins.com/ ` Ins代理
访问Pixiv, Instagram可以用现存免费代理，朋友，另外，Pixiv和Ins的cdn域名都可以通过改Host来访问。（尽管慢的要死）
