### ISSUE TITLE
按照教程去搭建了代理，突然访问不了了

### ISSUE THREAD

**Issue by wy150150** [EtherDream/jsproxy#205]
下面2张图是cloudflare内点击进去的
![image](https://user-images.githubusercontent.com/39988489/71320855-61358280-24ec-11ea-8287-505ece52c8a3.png)
![image](https://user-images.githubusercontent.com/39988489/71320859-67c3fa00-24ec-11ea-81a3-f5a69e7dad7c.png)

下图是直接用chrome直接访问url就是返回404
![image](https://user-images.githubusercontent.com/39988489/71320888-eae55000-24ec-11ea-938f-299ccca5e42d.png)

why？
被和谐了吗？

ps：刚搭好的时候，用浏览器直接url是可以的，但是加载很慢。出去一趟后就不行了，但是用cf点击图标链接的可以，而且还很快。

**Comment by lvfeijun** [comment]
我也是这样~求高手们指导…😂

**Comment by GameDun** [comment]
被河蟹了，大伙洗洗睡吧

**Comment by ivan-hz** [comment]
河蟹好久了。。。这个早就不行了。。。v2吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GameDun"<notifications@github.com&gt;; 
发送时间: 2019年12月23日(星期一) 上午10:47
收件人: "EtherDream/jsproxy"<jsproxy@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [EtherDream/jsproxy] 按照教程去搭建了代理，突然访问不了了 (#205)




被河蟹了，大伙洗洗睡吧

**Comment by wy150150** [comment]
都是这样，没有一点办法？？

**Comment by wy150150** [comment]
尼玛，又可以用了
![image](https://user-images.githubusercontent.com/39988489/71350389-301c8700-25ac-11ea-9be5-bb86b03319ba.png)

**Comment by lvfeijun** [comment]
![Screenshot_2019-12-23-18-28-16-998_com android chrome](https://user-images.githubusercontent.com/51140220/71352767-2007a600-25b2-11ea-947a-aea7a2802c24.jpg)
并提示invalid cookie这个是什么意思？

**Comment by wy150150** [comment]
下午可以用域名访问，18点又不能用了
cf点链接进去的一直可以使用
