### ISSUE TITLE
cloudflare上无法创建jsproxy的“worker”

### ISSUE THREAD

**Issue by nimdabd** [EtherDream/jsproxy#207]
卡在自定义域名那个地方，自定义完域名之后，点确认按钮，然后网站给我返回:It looks like we're having some internal issues.
Our team has been notified. If you'd like to help, tell us what happened below

分别用两个信箱注册两个账号都是如此，有和我一样的吗？我是用国内ip直连这个网站的。

**Comment by kinglyl** [comment]
一般情况下你需要刷新或者重新登陆，还是不行就fq

**Comment by kinglyl** [comment]
https://52sec.top
https://52proxy.fun
https://52proxy.fun/ytb/
我的博客，有搭建教程
Oriole隐私浏览，支持看视频。
Oriole视频下载，代理直下。

**Comment by nimdabd** [comment]
多谢楼上的回复！
二楼所说的方法都试啦，退出再重新登陆，用不同的浏览器登陆，fq登陆不显示登录那个界面，感觉内地ip登陆创建“worker”似乎被封杀了似的。

**Comment by nimdabd** [comment]
多谢楼上的回复！
二楼所说的方法都试啦，退出再重新登陆，用不同的浏览器登陆，fq登陆不显示登录那个界面，感觉内地ip登陆创建“worker”似乎被封杀了似的。

**Comment by nimdabd** [comment]
有小伙伴和我一样的吗？

**Comment by nimdabd** [comment]
有和我一样遭遇的小伙伴吗？

**Comment by nimdabd** [comment]
有和我一样遭遇的小伙伴吗？

**Comment by kinglyl** [comment]
没准你需要改变一下代码。。。这样cf就不能发现了？
