### ISSUE TITLE
目前在自己的VPS部署,访问youtube,页面内容加载不出来

### ISSUE THREAD

**Issue by shenqizhi** [EtherDream/jsproxy#213]
如题, 恳请大佬们告知解决方法,谢谢
![image](https://user-images.githubusercontent.com/32361081/72144937-6479ab00-33d4-11ea-9526-32d53480e4c8.png)

**Comment by kinglyl** [comment]
worker版本的也一样
我推荐你用这个
[Oriole-Proxy 黄鹂在线代理](https://52proxy.fun)

**Comment by sam-netizen** [comment]
@kinglyl
推荐在线代理，不错。
感谢你
