### ISSUE TITLE
建议关闭演示服务

### ISSUE THREAD

**Issue by doraven** [EtherDream/jsproxy#22]

**Comment by EtherDream** [comment]
正在实现白名单，以后只允许访问 google 等资料查询网站，其他的都会阻止。

**Comment by binbin666** [comment]
> 正在实现白名单，以后只允许访问 google 等资料查询网站，其他的都会阻止。

建议加紧步伐…而且还是github.io……

**Comment by rockmenjack** [comment]
这样很容让github吃河蟹啊，先关了吧

**Comment by xudongdong** [comment]
关了吧

**Comment by EtherDream** [comment]
github.io 只是一个用来显示的域名而已，真正的流量完全不涉及 github 的，用 curl 可以看到 github 返回的只是个几百字节的 404 页面。无浏览器能力的工具（扫描器、爬虫等）是看不到这个网站的数据的，之前也考虑过这个问题了。

另外 .github.io 是个顶级域后缀，和 .com/.cn 一样，不会因为一个 xxx.com 屏蔽所有 .com。当然之后会转移到其他域名上。

**Comment by doraven** [comment]
不是担心自动检测的技术问题，主要是两点，一是好事之徒大发宣扬，引起重视，直接和谐github.io；二是直接张贴代理服务来源，增加搬瓦工和其他主机提供商下的其他用户被和谐风险。shadowsocks连master branch都不敢显示出来，国内vpn这两年和谐的这么厉害，还是低调小众的好，口口相传就行

**Comment by EtherDream** [comment]
好的，我换个域名。

**Comment by whtiehack** [comment]
大佬  加个你那个 tk域名吧  @EtherDream

**Comment by vitoland** [comment]
> 
> 
> 好的，我换个域名。

不开新的，写这好了。是不是还有什么隐藏配置/步骤啊，无论怎么弄都无法加载数据，提示fetch跨域，但我看api配置里已经设置了啊。

**Comment by EtherDream** [comment]
> > 好的，我换个域名。
> 
> 不开新的，写这好了。是不是还有什么隐藏配置/步骤啊，无论怎么弄都无法加载数据，提示fetch跨域，但我看api配置里已经设置了啊，proxy.log里显示全是404。

nginx.conf 里的 DNS 改成 1.1.1.1 试试？

**Comment by hezhizheng** [comment]
都是相劝的声音

> 正在实现白名单，以后只允许访问 google 等资料查询网站，其他的都会阻止。

这样是延续Google蜻蜓计划的精神吗 :smirk:

**Comment by f2sky** [comment]
我就拿来用用Google搜索，梯子全挂，技术小白在大关网时期最后的哀鸣……

**Comment by zgayjjf** [comment]
最近比较敏感。
建议楼主：
1. 把项目转成团队项目，然后把个人账号和项目的关系给切割。
2. 把自己其他社交平台相关介绍删除，换成和自己不相关的账号。

造福大家的同时，一定要保护好自己。
感谢楼主。
