### ISSUE TITLE
ios chrome浏览器不支持，最新版本的。

### ISSUE THREAD

**Issue by whtiehack** [EtherDream/jsproxy#23]

**Comment by pixcat8102** [comment]
用系统自带的Safari可以。
试了下我在ios上不能播放视频换到Android就可以……

**Comment by breakwa2333** [comment]
ios 平台统一被迫使用旧版的safari webkit，本质上是套壳，由于最近safari才支持service worker所以其他浏览器暂时或者永远无法更上（看苹果脸色行事）
