### ISSUE TITLE
关于部署在自己的github.io域名的问题

### ISSUE THREAD

**Issue by JimmyTinsley** [EtherDream/jsproxy#24]
大佬你好,
我因为公司电脑的域名限制, 无法访问自己的个人域名, 只能够访问*.github.io的域名, 所以只能部署在自己的github.io域名下, 想问下大佬这样操作的具体细节.

1. 如果想要部署在自己的github.io域名, 请问nginx.conf应该如何填写配置? 需要生成证书吗?
2. 浏览器端`proxy/src/conf.js`里面, `NODE_MAP`是直接填写VPS的id和端口吗? 端口是否为服务端nginx.conf里面设置的监听端口?

问题有点多, 期望解答! 谢谢大佬

**Comment by EtherDream** [comment]
github.io 只能放静态资源，接口没法用 github.io 的。当然你可以自己绑定 host 把 xx.github.io 对应到后台接口服务器上，然后给 xx.github.io 自签一个证书。

**Comment by JimmyTinsley** [comment]
我的意思就是接口服务器部署在自己的VPS上, 然后用github.io存放静态资源, 只是想用它的域名. 麻烦再问下, 要怎么给自己的github.io签证书? 似乎无法操作它的dns...?

**Comment by EtherDream** [comment]
演示的方案就是“接口服务器部署在自己的VPS上, 然后用github.io存放静态资源”。

你说“公司电脑的域名限制, 无法访问自己的个人域名, 只能够访问*.github.io的域名”，那么自己的VPS域名解析不出来，所以说在本地把 xx.github.io 的域名绑定成你的 VPS IP。

**Comment by JimmyTinsley** [comment]
不好意思, 可能是我没表达清楚.
我现在的目标就是想把大佬你的演示方案部署在自己的VPS和github.io域名下, 但是不知道哪一步出了问题, 一直显示内容损坏错误. 我大概的配置步骤如下:

1. 创建新的jsproxy用户, clone项目,执行`./nginx-setup.sh`安装nginx.
2. 只修改了`nginx.conf`中的`server_name`为自己的`xx.github.io`域名, 监听端口为默认的`8080`不变. 其他配置项均未更改.
3. `git clone`了jsproxy-browser项目, 在`proxy/src/conf.js`新增了`NODE_MAP`, 地址为`xxx.xxx.xxx.xxx:8080`(我的VPS IP), 对应修改了`NODE_DEF`. 然后执行了`proxy/debug.sh`.
4. 在`home/index.html`中修改了selNode元素, 新增了上面添加的`NODE_MAP`, 然后执行了`home/build.sh`.
5. 将生成的www目录内的内容push到xxx.github.io仓库里面.

防火墙的8080端口确认是开放着的. 用火狐浏览器访问会得到如下页面
![图片](https://user-images.githubusercontent.com/37508117/56777598-0afd2c00-6805-11e9-8fd3-d7d75ac3c767.png)
proxy.log中的日志记录的后面三个数字是 0  303 和 400

如有错误, 烦请指出!

**Comment by EtherDream** [comment]
后端：先申请一个域名 example.com，修改 nginx.conf 中的 server_name 为 example.com。然后给 example.com 申请证书（参考 gen-cert 目录或者去 sslforfree 网站申请）。把注释的那几行打开 8443。

前端：proxy/src/conf.js 里设置的是 example.com（不是 IP！因为 IP 地址没法申请免费证书）

**Comment by JimmyTinsley** [comment]
谢谢, 了解了
