### ISSUE TITLE
Docker化jsproxy

### ISSUE THREAD

**Issue by qfdk** [EtherDream/jsproxy#25]
Hi，

感谢作者的辛勤努力，看到这个项目感觉 还是很神奇的。 
分前后端来进行操作，后端要启动一个nginx，来监听特定的端口，前端需要连接到这里。

我想如果Docker化成一个简单的容器，这样操作会不会更统一和方便，这样避免在不同环境下碰到依赖缺失问题，已经端口被占用的问题。

Dockerfile 已经完成，并添加了一键脚本，方便的话merge之后您做一下rebase吧，开发的时候忘记开个分支了。

真诚的。

**Comment by EtherDream** [comment]
我这边还在不断的加功能，过几天我合进来哈哈

**Comment by qfdk** [comment]
@EtherDream 好的 我这边看看也优化一下，把镜像换成alpine。 感谢辛勤努力我也愿意出一份力

**Comment by yswtrue** [comment]
期待docker镜像

**Comment by wideweide** [comment]
@EtherDream 有官网的docker版本了吗？
下载了 https://hub.docker.com/r/tarove/jsproxy，感觉用不起来
docker run -itd  --restart=always \
 -p 8241:8443 \
 --name jsproxy \
 tarove/jsproxy:latest

-----

后端其实就是用nginx配置一个正向代理就ok了吧？

前端拦截请求并转发到到后端的正向代理？


@qfdk 你的版本是否一键可用？

**Comment by bugfan** [comment]
> 

你确定是正向代理？？😂
