### ISSUE TITLE
一键配置的时候报错，80端口不可用，但其实是可用的

### ISSUE THREAD

**Issue by Jarvis110469** [EtherDream/jsproxy#261]
[https://img.omyh.net/imgs/2020/05/a285b58ebd3b3191.jpg](url)
如图所示，求教

**Comment by Jarvis110469** [comment]
https://img.omyh.net/imgs/2020/05/a285b58ebd3b3191.jpg

**Comment by wangdaima** [comment]
我也是这个问题，期待大神回复

**Comment by Jarvis110469** [comment]
> 我也是这个问题，期待大神回复

我看你还在回复别人的提问 以为你都知道呢，唉，期待大神解决，我自己有证书的，可惜不能先配置好在手动添加证书

**Comment by wangdaima** [comment]
证书怎么搞得？有教程没？

**Comment by Jarvis110469** [comment]
> 证书怎么搞得？有教程没？

我就是用dnspod买的免费证书啊
