### ISSUE TITLE
js和css无法加载

### ISSUE THREAD

**Issue by vitoland** [EtherDream/jsproxy#27]
你的演示站可以加载js和css，但源码搭建的不行。
是不是还有什么配置调整了但源码里没有反馈出来

**Comment by EtherDream** [comment]
被代理页面的 JS 和 CSS 无法加载吗？

**Comment by vitoland** [comment]
是的。
测试站 proxy.liyunbin.com

**Comment by EtherDream** [comment]
把服务端 nginx.conf 里的 `http2` 选项关闭再试一下？我发现有些 js 文件的请求会报错：
```
* HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by vitoland** [comment]
> 
> 
> 被代理页面的 JS 和 CSS 无法加载吗？

冤枉作者了，原来的测试在一个俄罗斯的VPS，版本 CentOS Linux release 7.6.1810 (Core)
换了一个美国的VPS，版本 CentOS Linux 7.2.1511 (Core)，没有问题了，不知道作者有没有兴趣拿那个VPS探究一下。
