### ISSUE TITLE
make 失败

### ISSUE THREAD

**Issue by chenshiforever** [EtherDream/jsproxy#29]
> `/home/jsproxy/server/openresty-1.15.8.1rc1/build/nginx-1.15.8/../ngx_stream_lua-0.0.6/src/ngx_stream_lua_regex.c:369: undefined reference to `pcre_assign_jit_stack'
objs/addon/src/ngx_stream_lua_regex.o: In function `ngx_stream_lua_ffi_set_jit_stack_size':
/home/jsproxy/server/openresty-1.15.8.1rc1/build/nginx-1.15.8/../ngx_stream_lua-0.0.6/src/ngx_stream_lua_regex.c:1961: undefined reference to `pcre_jit_stack_free'
/home/jsproxy/server/openresty-1.15.8.1rc1/build/nginx-1.15.8/../ngx_stream_lua-0.0.6/src/ngx_stream_lua_regex.c:1968: undefined reference to `pcre_jit_stack_alloc'
collect2: ld returned 1 exit status
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory `/home/jsproxy/server/openresty-1.15.8.1rc1/build/nginx-1.15.8'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/jsproxy/server/openresty-1.15.8.1rc1/build/nginx-1.15.8'
make: *** [all] Error 2
`
这里make失败了，然后我也不知道咋办了~

**Comment by chenshiforever** [comment]
centos6

**Comment by chenshiforever** [comment]
prce的问题，需要自己手动下一prce

**Comment by chenshiforever** [comment]
哇。意思就是centos6安不上咯。。。伤心，最低要求prce>8

**Comment by EtherDream** [comment]
把 setup-nginx.sh 里的  --with-pcre-jit 删除好了。现在 nginx.conf 里都没用到正则，这个选项还是之前版本遗留下来的。。。

**Comment by EtherDream** [comment]
已更新。删除了 --with-pcre-jit

**Comment by chenshiforever** [comment]
其实删除了一样抱同样的错误，搜了很多我呢张没找到解决方案，估计只能升级centos7，我的是centos6.9

**Comment by EtherDream** [comment]
--without-pcre 试试？

**Comment by chenshiforever** [comment]
同样，没有任何效果

**Comment by EtherDream** [comment]
不加任何参数也编译不了？

**Comment by chenshiforever** [comment]
是的，我把所有参数都删了，还是在同一个地方报错，似乎是这个系统的问题。。

EtherDream <notifications@github.com> 于2019年5月1日周三 下午10:15写道：
