### ISSUE TITLE
GitHub Pages配置问题

### ISSUE THREAD

**Issue by forxi** [EtherDream/jsproxy#291]
我自定义了域名，访问问题如图：
访问首页是没问题的
![1](https://user-images.githubusercontent.com/51847600/99161326-2f449480-272c-11eb-9d75-9527349e7b47.jpg)
但是访问其他的就是404了
![2](https://user-images.githubusercontent.com/51847600/99161333-42effb00-272c-11eb-9c9a-a36cbb51f6bc.jpg)
是gh-pages分支的conf.js要修改什么吗？

**Comment by wehnhew** [comment]
请问怎么解决的？

**Comment by wehnhew** [comment]
> 我自定义了域名，访问问题如图：
> 访问首页是没问题的
> ![1](https://user-images.githubusercontent.com/51847600/99161326-2f449480-272c-11eb-9d75-9527349e7b47.jpg)
> 但是访问其他的就是404了
> ![2](https://user-images.githubusercontent.com/51847600/99161333-42effb00-272c-11eb-9c9a-a36cbb51f6bc.jpg)
> 是gh-pages分支的conf.js要修改什么吗？

请问怎么解决的？
