### ISSUE TITLE
请求在交给WS处理过程中有做加密处理吗？

### ISSUE THREAD

**Issue by cedooo** [EtherDream/jsproxy#30]

**Comment by EtherDream** [comment]
WS -> WebSocket？还是 SW？现在没有任何加密，依赖浏览器 HTTPS。

**Comment by chenlang888881** [comment]
所有请求是走https，等于是加密处理对吧，这种会不会导致封ip。

**Comment by chenlang888881** [comment]
还有我发现代理访问CSDN时，貌似会自动跳到www.csdn.net 上面去

**Comment by cedooo** [comment]
ws,打错了。

**Comment by EtherDream** [comment]
> 还有我发现代理访问CSDN时，貌似会自动跳到www.csdn.net 上面去

能提供个复现的页面吗？CSDN 那个跳转的案例之前是解决了的。

**Comment by cedooo** [comment]
sw，打错了
