### ISSUE TITLE
到底有没有人安装成功过啊？

### ISSUE THREAD

**Issue by fishfree** [EtherDream/jsproxy#308]
我怎么折腾都不行。安装倒是顺利的，没有报错。但访问 http://myname.com:8080时自动跳转到https://myname.com:8443 但要命的是nginx并未在8443端口上跑起来。怀疑我还是没能真正安装好。谁能给一个一步一步的操作指南啊？先谢过了！

**Comment by fishfree** [comment]
发现是我自己的问题

**Comment by bbhxwl** [comment]
我centos7 也一直没成功
