### ISSUE TITLE
为什么./-----$WantProxyWebsite$有5个-啊

### ISSUE THREAD

**Issue by neila-a** [EtherDream/jsproxy#313]
假如想访问的话，是./-----后面加网站，比如`[./-----google.com](./-----jsproxy)`啊！
直接`./Google.com`或`./?url="Google.com"`不香吗？？？

**Comment by Yandexkg** [comment]
你是怕你域名多不够墙吃？

**Comment by neila-a** [comment]
那当然了

在 2021-05-23 12:50:38，Yandexkg ***@***.***> 写道：


你是怕你域名多不够墙吃？

**Comment by by-justin** [comment]
因為除了 jsproxy, 沒有其他網站的 url 裡面會包含五個 “-”

按照你的寫法, 如果我訪問 `jump.example.com/?url=example.com`, url 就會變成 `jsproxy.xxx.com/?url=jump.example.com/?url=example.com`, 然後 jsproxy 就會在兩個網址間左右橫跳, 然後報錯: too many redirections.
我建議你提 issue 之前先改掉試一下, 比如說把 ----- 改為 ?, 然後看看會發生什麼.
