### ISSUE TITLE
推荐一个超级牛逼的

### ISSUE THREAD

**Issue by allmors** [EtherDream/jsproxy#326]

**Comment by wll8** [comment]
如何使用呢？进入就只有输入密码？

**Comment by wll8** [comment]
开源吗？

**Comment by allmors** [comment]
> 开源吗？

据作者说后期会

**Comment by wishstrive** [comment]
what is the password?

**Comment by wll8** [comment]
超级不稳定
![image](https://user-images.githubusercontent.com/28223260/194790004-c5c01d5b-51c5-4ec9-9906-b3f7d544aefb.png)

**Comment by Qiuyebai-1226** [comment]
不能直接用cf workers，需要额外的vps
