### ISSUE TITLE
docker 镜像，支持 x86_64 和 arm/v8

### ISSUE THREAD

**Issue by manooog** [EtherDream/jsproxy#329]
最近将 jsproxy 构建成了 docker 镜像，方便新手朋友进行部署测试。感兴趣的话查看这个项目：

https://github.com/manooog/jsproxy-docker

内有简单的部署说明。

**Comment by jsjcjsjc** [comment]
测试了一下显示需要https,反代后又不能访问~~搞不懂

**Comment by jsjcjsjc** [comment]
貌似是8443端口不能访问

**Comment by manooog** [comment]
> 貌似是8443端口不能访问

我文档里面写的反代是指向 8080 端口的。你提到 8443端口不能访问主要有两个可能性：

1、docker run xxx 的时候没有将 8443 端口暴露出来

2、如果想要使用容器的 8443 端口，那意味着需要在容器内配置好 https 证书。

我更推荐在反向代理服务器中配置好 https 证书，然后反向代理到容器 8080 端口。

**Comment by jsjcjsjc** [comment]
感谢不过越来越不明白了了，我以为设置宝塔的ssl反向代理后就开箱即用了。
不管怎么说感谢分享

**Comment by manooog** [comment]
> 感谢不过越来越不明白了了，我以为设置宝塔的ssl反向代理后就开箱即用了。 不管怎么说感谢分享

你试试直接代理 8080 端口，

**Comment by jsjcjsjc** [comment]
老哥,这不是你写的嘛~~
`jsproxy 使用了浏览器的 Service workers 能力。出于安全考量，Service workers 只能由 HTTPS 承载，毕竟修改网络请求的能力暴露给中间人攻击会非常危险。在 Firefox 浏览器的用户隐私模式，Service Worker 不可用。`

**Comment by manooog** [comment]
> 老哥,这不是你写的嘛~~ `jsproxy 使用了浏览器的 Service workers 能力。出于安全考量，Service workers 只能由 HTTPS 承载，毕竟修改网络请求的能力暴露给中间人攻击会非常危险。在 Firefox 浏览器的用户隐私模式，Service Worker 不可用。`

浏览器    ----https---->   nginx    ----proxy---->   jsproxy:8080

所以浏览器还是https 访问，安全的

**Comment by thomas-art** [comment]
很奇怪，我配置之后访问直接301跳转到8443端口，然后就是访问拒绝

**Comment by 17huiwei** [comment]
我也遇到同样的问题，无论如何都会跳出8443端口。
