### ISSUE TITLE
无法登陆Google账号

### ISSUE THREAD

**Issue by marsvet** [EtherDream/jsproxy#34]
为啥用jsproxy访问Google，YouTube等网站无法登陆Google账号😔。在Google账号登陆页面点击下一步没有反应，手机电脑都不行。

**Comment by EtherDream** [comment]
程序还有问题。。这个 BUG 一直没找到~

**Comment by marsvet** [comment]
不管怎么样，感谢作者的贡献，膜拜大佬🙏
