### ISSUE TITLE
ERROR: origin `` is not allowed

### ISSUE THREAD

**Issue by createWheel** [EtherDream/jsproxy#36]
浏览器 显示 `ERROR: origin `` is not allowed`
我感觉事我配置了 `allowed-sites.conf` 这个文件有问题.. 我添加了需要配置的域名，可是没用，改了很久也不知道为什么

**Comment by EtherDream** [comment]
你怎么配置的

**Comment by createWheel** [comment]
依旧，我是小白，哈哈哈

**Comment by EtherDream** [comment]
我知道了，你把代理服务和静态文件服务放在同个域名下是吧~

**Comment by MCshenhua** [comment]
我也是这个问题，“把代理服务和静态文件服务放在同个域名下”是什么意思？
