### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by c0py7hat** [EtherDream/jsproxy#39]
安装好几次了都没成功郁闷啊。。
我用的手动安装的
![image](https://user-images.githubusercontent.com/48747142/57767123-3ce61c00-773b-11e9-9644-64708f3730a5.png)
但是fa访问IP没反应，家端口也没反应，页面提供的#local换成自己IP也没用
一键脚本也不知道什么东西运行了都提示都在运行，但是访问也不行
必须要搭建玩WEB端才能测试？

**Comment by zanzhz1101** [comment]
是的

**Comment by c0py7hat** [comment]
SecurityError: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.

搭建完web端提示这个，证书我也放了.

**Comment by c0py7hat** [comment]
> 是的

SecurityError: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.

搭建完web端提示这个，证书我也放了.

**Comment by EtherDream** [comment]
一键脚本执行后已经开启服务了。如果是在本地虚拟机里测试的话，可以用那个 #local 的页面访问。如果是在 VPS 上的话，需要申请证书，然后修改 nginx.conf，搭建前端页面才可以。

目前 VPS 测试比较麻烦，我考虑加一个可以远程测试的节点吧。。

**Comment by c0py7hat** [comment]
> 一键脚本执行后已经开启服务了。如果是在本地虚拟机里测试的话，可以用那个 #local 的页面访问。如果是在 VPS 上的话，需要申请证书，然后修改 nginx.conf，搭建前端页面才可以。
> 
> 目前 VPS 测试比较麻烦，我考虑加一个可以远程测试的节点吧。。

好的，谢谢。
目前问题是我vps手动搭建了服务端，另一台vps搭建了web端，然后我没用域名，直接用的IP访问。
主要是比较错乱，搞得我自己头都晕了不知道修改哪，没有比较完整详细的步骤，也可能我太菜了

开始看到更新了，增加了一键脚本，以为春天来了，结果一看是..服务端脚本，差点以为是一键傻瓜脚本了。。

**Comment by EtherDream** [comment]
> > 一键脚本执行后已经开启服务了。如果是在本地虚拟机里测试的话，可以用那个 #local 的页面访问。如果是在 VPS 上的话，需要申请证书，然后修改 nginx.conf，搭建前端页面才可以。
> > 目前 VPS 测试比较麻烦，我考虑加一个可以远程测试的节点吧。。
> 
> 好的，谢谢。
> 目前问题是我vps手动搭建了服务端，另一台vps搭建了web端，然后我没用域名，直接用的IP访问。
> 主要是比较错乱，搞得我自己头都晕了不知道修改哪，没有比较完整详细的步骤，也可能我太菜了
> 
> 开始看到更新了，增加了一键脚本，以为春天来了，结果一看是..服务端脚本，差点以为是一键傻瓜脚本了。。

客户端的一键安装+测试比较麻烦，因为涉及到 HTTPS 问题。在考虑加一个公开的证书专门用于测试。

刚刚更新了 README，你看下远程测试的命令。

**Comment by c0py7hat** [comment]
> > > 一键脚本执行后已经开启服务了。如果是在本地虚拟机里测试的话，可以用那个 #local 的页面访问。如果是在 VPS 上的话，需要申请证书，然后修改 nginx.conf，搭建前端页面才可以。
> > > 目前 VPS 测试比较麻烦，我考虑加一个可以远程测试的节点吧。。
> > 
> > 
> > 好的，谢谢。
> > 目前问题是我vps手动搭建了服务端，另一台vps搭建了web端，然后我没用域名，直接用的IP访问。
> > 主要是比较错乱，搞得我自己头都晕了不知道修改哪，没有比较完整详细的步骤，也可能我太菜了
> > 开始看到更新了，增加了一键脚本，以为春天来了，结果一看是..服务端脚本，差点以为是一键傻瓜脚本了。。
> 
> 客户端的一键安装+测试比较麻烦，因为涉及到 HTTPS 问题。在考虑加一个公开的证书专门用于测试。
> 
> 刚刚更新了 README，你看下远程测试的命令。

好的，主要是我搭建失败三次了...太蛋疼了。
话说证书不能用let's encrypt这个吗，我刚才直接用的宝塔导入的www。gen文件夹的sh脚本无法生成证书，我就从bt里面自动申请证书手动保存到cert目录，貌似没啥用。

**Comment by EtherDream** [comment]
> > > > 一键脚本执行后已经开启服务了。如果是在本地虚拟机里测试的话，可以用那个 #local 的页面访问。如果是在 VPS 上的话，需要申请证书，然后修改 nginx.conf，搭建前端页面才可以。
> > > > 目前 VPS 测试比较麻烦，我考虑加一个可以远程测试的节点吧。。
> > > 
> > > 
> > > 好的，谢谢。
> > > 目前问题是我vps手动搭建了服务端，另一台vps搭建了web端，然后我没用域名，直接用的IP访问。
> > > 主要是比较错乱，搞得我自己头都晕了不知道修改哪，没有比较完整详细的步骤，也可能我太菜了
> > > 开始看到更新了，增加了一键脚本，以为春天来了，结果一看是..服务端脚本，差点以为是一键傻瓜脚本了。。
> > 
> > 
> > 客户端的一键安装+测试比较麻烦，因为涉及到 HTTPS 问题。在考虑加一个公开的证书专门用于测试。
> > 刚刚更新了 README，你看下远程测试的命令。
> 
> 好的，主要是我搭建失败三次了...太蛋疼了。
> 话说证书不能用let's encrypt这个吗，我刚才直接用的宝塔导入的www。gen文件夹的sh脚本无法生成证书，我就从bt里面自动申请证书手动保存到cert目录，貌似没啥用。

用 acme.sh 生成更方便，可以自动更新。那个工具 root 安装需要的，网上很多案例。

**Comment by c0py7hat** [comment]
> > > > > 一键脚本执行后已经开启服务了。如果是在本地虚拟机里测试的话，可以用那个 #local 的页面访问。如果是在 VPS 上的话，需要申请证书，然后修改 nginx.conf，搭建前端页面才可以。
> > > > > 目前 VPS 测试比较麻烦，我考虑加一个可以远程测试的节点吧。。
> > > > 
> > > > 
> > > > 好的，谢谢。
> > > > 目前问题是我vps手动搭建了服务端，另一台vps搭建了web端，然后我没用域名，直接用的IP访问。
> > > > 主要是比较错乱，搞得我自己头都晕了不知道修改哪，没有比较完整详细的步骤，也可能我太菜了
> > > > 开始看到更新了，增加了一键脚本，以为春天来了，结果一看是..服务端脚本，差点以为是一键傻瓜脚本了。。
> > > 
> > > 
> > > 客户端的一键安装+测试比较麻烦，因为涉及到 HTTPS 问题。在考虑加一个公开的证书专门用于测试。
> > > 刚刚更新了 README，你看下远程测试的命令。
> > 
> > 
> > 好的，主要是我搭建失败三次了...太蛋疼了。
> > 话说证书不能用let's encrypt这个吗，我刚才直接用的宝塔导入的www。gen文件夹的sh脚本无法生成证书，我就从bt里面自动申请证书手动保存到cert目录，貌似没啥用。
> 
> 用 acme.sh 生成更方便，可以自动更新。那个工具安装需要 root 权限，网上很多案例。

好吧，对了，web端只需要把www文件放到空间，其他文件就不用管了是吗

**Comment by goxofy** [comment]
> > > > > > 一键脚本执行后已经开启服务了。如果是在本地虚拟机里测试的话，可以用那个 #local 的页面访问。如果是在 VPS 上的话，需要申请证书，然后修改 nginx.conf，搭建前端页面才可以。
> > > > > > 目前 VPS 测试比较麻烦，我考虑加一个可以远程测试的节点吧。。
> > > > > 
> > > > > 
> > > > > 好的，谢谢。
> > > > > 目前问题是我vps手动搭建了服务端，另一台vps搭建了web端，然后我没用域名，直接用的IP访问。
> > > > > 主要是比较错乱，搞得我自己头都晕了不知道修改哪，没有比较完整详细的步骤，也可能我太菜了
> > > > > 开始看到更新了，增加了一键脚本，以为春天来了，结果一看是..服务端脚本，差点以为是一键傻瓜脚本了。。
> > > > 
> > > > 
> > > > 客户端的一键安装+测试比较麻烦，因为涉及到 HTTPS 问题。在考虑加一个公开的证书专门用于测试。
> > > > 刚刚更新了 README，你看下远程测试的命令。
> > > 
> > > 
> > > 好的，主要是我搭建失败三次了...太蛋疼了。
> > > 话说证书不能用let's encrypt这个吗，我刚才直接用的宝塔导入的www。gen文件夹的sh脚本无法生成证书，我就从bt里面自动申请证书手动保存到cert目录，貌似没啥用。
> > 
> > 用 acme.sh 生成更方便，可以自动更新。那个工具安装需要 root 权限，网上很多案例。
> 
> 好吧，对了，web端只需要把www文件放到空间，其他文件就不用管了是吗

需要生成静态文件，主要是x.js

**Comment by c0py7hat** [comment]
> > > > > > > 一键脚本执行后已经开启服务了。如果是在本地虚拟机里测试的话，可以用那个 #local 的页面访问。如果是在 VPS 上的话，需要申请证书，然后修改 nginx.conf，搭建前端页面才可以。
> > > > > > > 目前 VPS 测试比较麻烦，我考虑加一个可以远程测试的节点吧。。
> > > > > > 
> > > > > > 
> > > > > > 好的，谢谢。
> > > > > > 目前问题是我vps手动搭建了服务端，另一台vps搭建了web端，然后我没用域名，直接用的IP访问。
> > > > > > 主要是比较错乱，搞得我自己头都晕了不知道修改哪，没有比较完整详细的步骤，也可能我太菜了
> > > > > > 开始看到更新了，增加了一键脚本，以为春天来了，结果一看是..服务端脚本，差点以为是一键傻瓜脚本了。。
> > > > > 
> > > > > 
> > > > > 客户端的一键安装+测试比较麻烦，因为涉及到 HTTPS 问题。在考虑加一个公开的证书专门用于测试。
> > > > > 刚刚更新了 README，你看下远程测试的命令。
> > > > 
> > > > 
> > > > 好的，主要是我搭建失败三次了...太蛋疼了。
> > > > 话说证书不能用let's encrypt这个吗，我刚才直接用的宝塔导入的www。gen文件夹的sh脚本无法生成证书，我就从bt里面自动申请证书手动保存到cert目录，貌似没啥用。
> > > 
> > > 
> > > 用 acme.sh 生成更方便，可以自动更新。那个工具安装需要 root 权限，网上很多案例。
> > 
> > 
> > 好吧，对了，web端只需要把www文件放到空间，其他文件就不用管了是吗
> 
> 需要生成静态文件，主要是x.js

你好，用什么生成呢，在哪个位置，谢谢哈

**Comment by goxofy** [comment]
那个repo里有个文档，按照那个操作

**Comment by c0py7hat** [comment]
> 那个repo里有个文档，按照那个操作

好的，谢谢
