### ISSUE TITLE
提个小建议，希望可以配置端口，而不是固定 443

### ISSUE THREAD

**Issue by whtiehack** [EtherDream/jsproxy#4]
希望只是开一个特殊的端口自己用。
不知道是否好实现？

**Comment by EtherDream** [comment]
我考虑一下，前端 JS 代码有些地方需要调整。

另外只是自己用的话，可以在 build.sh 里把 PORT 变量 443 改成 4430，然后执行：
```
iptables -t nat -I PREROUTING -p tcp --src x.x.x.0/24 --dport 443 -j REDIRECT --to-ports 4430
```
我一直就是用这个办法，在同个机器上开两个服务。普通用户访问正常版，自己访问调试版。

**Comment by whtiehack** [comment]
我研究研究 谢谢

**Comment by linsir** [comment]
@EtherDream 你的微博怎么不见了？

**Comment by EtherDream** [comment]
> @EtherDream 你的微博怎么不见了？

不知什么情况被封了，所有帖子都被删了

**Comment by linsir** [comment]
@EtherDream 这也太可恶啊，我一直收藏了很多你的#前端黑魔法#，请问还有备份吗？

**Comment by EtherDream** [comment]
> @EtherDream 这也太可恶啊，我一直收藏了很多你的#前端黑魔法#，请问还有备份吗？

有备份的，改天整理下放到仓库里。不过评论和转发都没了。。。

**Comment by linsir** [comment]
@EtherDream 好的， 感谢。
