### ISSUE TITLE
关于通过/index.html访问的需求

### ISSUE THREAD

**Issue by zanzhz1101** [EtherDream/jsproxy#40]
关于通过/index.html访问的需求
js路径会变为//x.js,网页路径变为
https://-----https//www.google.com
大佬有空改一下就好

**Comment by EtherDream** [comment]
晚上我更新下

**Comment by zanzhz1101** [comment]
好的大佬

**Comment by zanzhz1101** [comment]
emmmm我试着直接通过对象存储的静态页面访问，http://t.cn/EKE2QPo，x.js等加载没问题，但是服务端的nginx可能是因为对象存储的域名过长导致nginx启动不起来，报错nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 64

**Comment by zanzhz1101** [comment]
暂时通过删掉_origin_id解决了，不过风险比较大

**Comment by EtherDream** [comment]
> emmmm我试着直接通过对象存储的静态页面访问，http://t.cn/EKE2QPo ，x.js等加载没问题，但是服务端的nginx可能是因为对象存储的域名过长导致nginx启动不起来，报错nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 64

配置 `map_hash_bucket_size 128;` 试试，参考 http://nginx.org/en/docs/http/ngx_http_map_module.html。

index.html 那个我还在测试，这次更新之后很多内容上 CDN 了，路径有很多变化

**Comment by EtherDream** [comment]
已添加这个功能，可以参考 jsproxy-browser 的 dev 分支

**Comment by zanzhz1101** [comment]
roger 
*
话说map_hash_bucket_size 128;应该加在哪呢，我加在http{后面显示 invalid number啥的

**Comment by EtherDream** [comment]
> roger
> *
> 话说map_hash_bucket_size 128;应该加在哪呢，我加在http{后面显示 invalid number啥的

http 块里没问题吧。不过现在不需要把 index.html 部署在那个长域名里了，可以找个空间只放 index.html、404.html、sw.js，把 asserts 目录放在 CDN

**Comment by zanzhz1101** [comment]
ok我试试现在的版本

**Comment by EtherDream** [comment]
> ok我试试现在的版本

dev 分支的文档还不完善。。。proxy/conf.js、proxy/release.sh 里要配 CDN 的 URL，有点小麻烦。。。

**Comment by zanzhz1101** [comment]
> > ok我试试现在的版本
> 
> dev 分支的文档还不完善。。。proxy/conf.js、proxy/release.sh 里要配 CDN 的 URL，有点小麻烦。。。

发现了，不过发现晚了哈哈，我直接改的release之后的文件，就是ico的cdn连接不知道在哪里改，所以直接删掉了（暴力解决）  https://jz.htp1.tk/ 现在已经搭建好了

**Comment by EtherDream** [comment]
> > > ok我试试现在的版本
> > 
> > 
> > dev 分支的文档还不完善。。。proxy/conf.js、proxy/release.sh 里要配 CDN 的 URL，有点小麻烦。。。
> 
> 发现了，不过发现晚了哈哈，我直接改的release之后的文件，就是ico的cdn连接不知道在哪里改，所以直接删掉了（暴力解决） https://jz.htp1.tk/ 现在已经搭建好了

我再改进下，打算做一个能动态加载的配置文件，CDN、节点、各种策略都放这里，不用每次打包 js

**Comment by zanzhz1101** [comment]
加上这一段吧哈哈，打包运行前请安装nodejs，安装npm，安装webpack，安装webpack-cli，安装 html-minifier，
sudo apt-get install nodejs npm
sudo npm install npm@latest -g
sudo npm install n -g
sudo n latest
sudo npm install webpack@latest webpack-cli@latest html-minifier@latest -g

**Comment by EtherDream** [comment]
> 加上这一段吧哈哈，打包运行前请安装nodejs，安装npm，安装webpack，安装webpack-cli，安装 html-minifier，
> sudo apt-get install nodejs npm
> sudo npm install npm@latest -g
> sudo npm install n -g
> sudo n latest
> sudo npm install webpack@latest webpack-cli@latest html-minifier@latest -g

不用了。以后不用自己打包，我准备把 conf.js 改成动态加载了
