### ISSUE TITLE
检测ipcalc的安装

### ISSUE THREAD

**Issue by qijianjun** [EtherDream/jsproxy#52]
ipcalc可能没有安装，这时安装证书会出现问题，所以是不是应该检测一下，并作相应处理？

**Comment by EtherDream** [comment]
好的，下次更新加上。

**Comment by qijianjun** [comment]
似乎ipcalc那句判断有问题，我发现一直返回“无效IP”的提示。

[OT]还有最好说明申请证书需要提前有服务（似乎不必须是http）在80端口运行，以保证端口转发成功，我仔细看了i.sh才搞明白为什么之前申请证书失败了。

**Comment by EtherDream** [comment]
看来还是用正则判断比较靠谱，ipcalc 输出内容不可靠。

申请证书之前，默认是启动自带那个服务的（`~/server/run.sh`）。端口是 10080，用 iptables 重定向 80 端口过来。不过 i.sh 执行结束后会删除重定向，估计这个原因导致没法申请成功。看来根本原因还是 ipcalc 那个检测的问题。

**Comment by qijianjun** [comment]
是的，我理解有错误，iptables重定向应该不需要提前有80端口open。但如果用权限不足的用户执行iptables命令，重定向就会失败。

比如这个场景：
用普通权限的用户直接运行`i.sh cert`，脚本就跳过了su和权限检查，且不在正确的工作目录。
而如果手动切换到jsproxy，并在正确的目录下执行i.sh，但若当前并没有80端口开启，即使ipcalc没问题，也无法获取证书，因为80端口根本无法开启。

**Comment by EtherDream** [comment]
`i.sh cert` 这个用法以后应该会去掉，之前调试时遗留的一个用法。目标还是自动安装能够一次完成。
