### ISSUE TITLE
请问如何使用 cf 的 worker 来搭建？

### ISSUE THREAD

**Issue by yanyuechuixue** [EtherDream/jsproxy#59]
我直接将  index.js 中的东西复制进去，发现并不 work。

多谢！

**Comment by EtherDream** [comment]
index.js 没法再 demo 页面里运行，需要开通 worker 服务，再设置 route。

**Comment by yanyuechuixue** [comment]
已经开通了 worker , 请教一下如何设置？

**Comment by EtherDream** [comment]
把代码复制进去，设置一个 url route，然后在 conf.js 里修改默认那个 cfworker 的 url 就可以了。 不过服务端默认是关闭的，需要把 https://github.com/EtherDream/jsproxy/blob/master/lua/http-enc-res-hdr.lua#L114 三行注释打开才有效果。

这个功能还在实验，以后我会写个文档。

**Comment by Dandelionss** [comment]
你好，我简略的写了 一个用worker部署的过程，地址：https://blog.qixiv.me/?p=posts%2F8.md
另外，用代理来访问推特、Github会出现乱码现象。

**Comment by EtherDream** [comment]
https://github.com/EtherDream/jsproxy/tree/master/cf-worker

**Comment by yanyuechuixue** [comment]
多谢！

**Comment by whtiehack** [comment]
TypeError: Failed to fetch  我部署一下出现这个。什么情况？ 大佬试一下哈  @EtherDream

**Comment by EtherDream** [comment]
线路选“当前站点”了吗

**Comment by whtiehack** [comment]
@EtherDream  好了。。。谢谢大佬。
