### ISSUE TITLE
是不是有点简单问题复杂化了?

### ISSUE THREAD

**Issue by 93Alliance** [EtherDream/jsproxy#6]
这种方式有点过于简单问题复杂化,作者真实的目的是什么呢?

**Comment by owen800q** [comment]
不会吧，之前看过类似项目，比这个更复杂，感觉这种代理方式作者已经简化了

**Comment by JiaJiaJiang** [comment]
同不明白目的，既然都需要部署nginx来反代了为何不直接部署一个代理服务器来实现代理呢？
或者说这就是为了在没有安装相关代理程序的情况下使用的？

**Comment by EtherDream** [comment]
> 同不明白目的，既然都需要部署nginx来反代了为何不直接部署一个代理服务器来实现代理呢？
> 或者说这就是为了在没有安装相关代理程序的情况下使用的？

是的。有时遇到没装客户端的电脑或手机，可以用网页版的凑合下。

**Comment by whtiehack** [comment]
这样就不需要装各种科学上网工具了，只是查查资料用，比较省事。

**Comment by whtiehack** [comment]
比如给公司内部用，很方便，你要知道还有很多码农不会科学上网的。

**Comment by EtherDream** [comment]
另外以后加上资源加速功能的话，速度可以比任何 SOCK/VPN 代理都快，静态资源可以直接从附近 CDN 加载，这个是底层代理实现不了。

**Comment by 93Alliance** [comment]
作者有时间和经历维护么？可以邀请一个有兴趣的一起搞啊

**Comment by xhqpp** [comment]
> > 同不明白目的，既然都需要部署nginx来反代了为何不直接部署一个代理服务器来实现代理呢？
> > 或者说这就是为了在没有安装相关代理程序的情况下使用的？
> 
> 是的。有时遇到没装客户端的电脑或手机，可以用网页版的凑合下。

请问手机如何使用？苹果手机可以吗？

**Comment by ddzy** [comment]
> > > 同不明白目的，既然都需要部署nginx来反代了为何不直接部署一个代理服务器来实现代理呢？
> > > 或者说这就是为了在没有安装相关代理程序的情况下使用的？
> > 
> > 
> > 是的。有时遇到没装客户端的电脑或手机，可以用网页版的凑合下。
> 
> 请问手机如何使用？苹果手机可以吗？

可以, 手机访问站点, 收藏起来就行了
