### ISSUE TITLE
请问如何在被代理页面获取用户的 IP

### ISSUE THREAD

**Issue by yccphp** [EtherDream/jsproxy#61]
## 场景

目前代理一些页面，存在跨域请求，发现 jsproxy 已经自动做了处理。

但是我发现了一些问题，首先是项目定义 **一个基于浏览器端 JS 实现的在线代理** ，我理解的是解决跨域时，是在本地起一个中转服务，然后由本地的中转服务去请求对应的服务器

但是我使用 jsproxy 代理了页面 A，然后发送了一个 POST 到页面 A

我在 POST 中打印了 SERVER ，得出内容如下

```
 [REMOTE_ADDR] => 47.240.15.226 
```

此 IP 并不是我电脑的外网 ip，查询处理是美国阿里云服务器的 ip 地址，推测是 demo 服务器

我想在被代理页面获取用户的 IP，请问该如何操作

**Comment by EtherDream** [comment]
「一个基于浏览器端 JS 实现的在线代理」主要是指这个代理大部分功能都是 JS 实现的，但是数据转发仍然需要一个服务器。被代理的页面看到的当然是我的服务器的 IP，用户 IP 是看不到的，因为没有加 XFF 之类的头。

**Comment by yccphp** [comment]
@EtherDream  谢谢您的解答，请问我想修改代码，在用户端发起 ajax 请求的时候不经过代理服务器，这样是否有实现的可能呢？因为我发现这个项目本身是为了解决用户端访问被墙的地址，通过这个中转，但是我很多的地址是用户端本身可以访问的，通过我中转是为了统计 pv,uv 之类的数据

**Comment by yccphp** [comment]
@EtherDream  您好，我想对此代码进行二次开发，不知能否提供 JS 部分的源文件呢？目前 github 上都是打包的资源，二次开发比较困难。谢谢您

**Comment by yccphp** [comment]
谢谢。已经找到源码，但并未解决我的问题

我希望的是在 network.js 中，直接对源站发起 POST 请求，我认为 serverWork 可以绕过跨域的限制。结果并不能

通过查看文档后发现，它可以通过 `cors` 来进行跨域请求。但是如果源站没有指定你可以请求的时候。依然被跨域限制

优势在于对比原始会少一次 option 请求

目前我的问题在修改了 api.conf 中反向代理部分后解决。

再次感谢这个项目
