### ISSUE TITLE
worker搭建的方式看油管会直接弹回油管首页

### ISSUE THREAD

**Issue by WXpiero** [EtherDream/jsproxy#68]
我搭建的步骤：
1复制https://github.com/XXX/jsproxy/blob/master/cf-worker/index.js的代码到Workers工作台
2进入我fork的gh-pages分支，编辑conf.js文件修改cfworker的url为我Workers的链接
3取消https://github.com/XXX/jsproxy/blob/master/lua/http-enc-res-hdr.lua#L114-L117的注释
打开github.io预览结果，油管未登陆状态下任意视频点开，黑色播放窗口出现几秒钟然后就弹回油管首页。如果是h5ai这样带密码的页面，就会提示TypeError: Failed to fetch。
worker的运行界面有这样6行错误提示：
Uncaught (in promise) TypeError: Cannot read property 'href' of null
    at proxy (worker.js:105)
    at handler (worker.js:94)
    at worker.js:21
Uncaught (in response) TypeError: Cannot read property 'href' of null
Uncaught (in promise) TypeError: Cannot read property 'href' of null
    at proxy (worker.js:105)
    at handler (worker.js:94)
    at worker.js:21
Uncaught (in response) TypeError: Cannot read property 'href' of null
Uncaught (in promise) TypeError: Cannot read property 'href' of null
    at proxy (worker.js:105)
    at handler (worker.js:94)
    at worker.js:21
Uncaught (in response) TypeError: Cannot read property 'href' of null
如果我用vps搭建，一键脚本总是申请证书失败（防火墙关闭，端口是通的，80也没有占用，全新安装的系统）

**Comment by EtherDream** [comment]
Workers 工作台用的是 https://cloudflareworkers.com/  吗？

**Comment by WXpiero** [comment]
是的，我试了我遇到的几种情况您的示例站也是一样的反应

**Comment by EtherDream** [comment]
https://cloudflareworkers.com/ 只是 cfworker 的临时演示页面，不是正式的工作台。正式的需要登录账号，在 Worker 面板栏里配置。除了复制代码，还要设置一个 route。

之前是需要付费的，现在好像每天有 10 万次免费请求。

**Comment by WXpiero** [comment]
我工作台是https://dash.cloudflare.com这个地址，对吗？

**Comment by EtherDream** [comment]
https://dash.cloudflare.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/域名/workers

**Comment by WXpiero** [comment]
haha,pull了静态资源的更新以后可以看油管了
