### ISSUE TITLE
第一行一直报错啊

### ISSUE THREAD

**Issue by lininn** [EtherDream/jsproxy#7]
在项目的根目录下新建 dnsconf 文件：

DOMAIN=example.com
DNS_ID=dns_xx
export xx_id=xxx
export xx_key=xxxxxx
'-d' is not a valid domain for parameter '-d'
[Thu Mar  7 21:24:24 EST 2019] '-d' is not a valid domain for parameter '-d'
[Thu Mar  7 21:24:24 EST 2019] '--key-file' is not a valid domain for parameter '-d'
[Thu Mar  7 21:24:24 EST 2019] '--ecc' is not a valid domain for parameter '-d'
./dnsconf: line 1: $'\377\376DOMAIN=xx.com\r': command not found

输入的是正常域名，这里xx表示

**Comment by whtiehack** [comment]
#1   参考这里试试。

**Comment by lininn** [comment]
./dnsconf: line 1: $'\377\376DNS_ID=dns_cf\r': command not found
[Thu Mar  7 22:01:38 EST 2019] '-d' is not a valid domain for parameter '-d'
[Thu Mar  7 22:01:38 EST 2019] '-d' is not a valid domain for parameter '-d'
[Thu Mar  7 22:01:38 EST 2019] '--key-file' is not a valid domain for parameter '-d'
[Thu Mar  7 22:01:38 EST 2019] '--ecc' is not a valid domain for parameter '-d'

**Comment by lininn** [comment]
ok,
