### ISSUE TITLE
没有处理 refresh 跳转

### ISSUE THREAD

**Issue by piaca** [EtherDream/jsproxy#70]
没有处理 `refresh: 3; url=https://example.com` 这种跳转

**Comment by EtherDream** [comment]
<meta http-equiv="refresh" content="refresh: 3; url=https://example.com"> 这种吗

**Comment by EtherDream** [comment]
有处理，不过写的有问题，我更新下。。。。

**Comment by piaca** [comment]
是 Response header 中的 Refresh。参考这里：http://www.otsukare.info/2015/03/26/refresh-http-header

**Comment by EtherDream** [comment]
> 是 Response header 中的 Refresh。参考这里：http://www.otsukare.info/2015/03/26/refresh-http-header

我加上这个

**Comment by piaca** [comment]
👍🏻
