### ISSUE TITLE
只有一个 set-cookie 时 cookie 不生效

### ISSUE THREAD

**Issue by piaca** [EtherDream/jsproxy#71]
多个 set-cookie，会在每个 set-cookie 前增加数字，当只有一个 set-cookie 时没做处理，造成 cookie 不生效

**Comment by EtherDream** [comment]
我看下。一个 cookie 的时候案例应该是 `--set-cookie`

**Comment by piaca** [comment]
但是 network.js 中判断 cookie 的逻辑 `const m = key.match(/^\d+-(.+)/)` 是忽略 `--set-cookie` 的

**Comment by EtherDream** [comment]
> 但是 network.js 中判断 cookie 的逻辑 `const m = key.match(/^\d+-(.+)/)` 是忽略 `--set-cookie` 的

确实有问题，我更新下。
