### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by kejicheng** [EtherDream/jsproxy#76]
脚本试了几次成功安装，登陆都是提示403 Forbidden。

**Comment by chen19870509** [comment]
常用改变用户执行权限
chown jsproxy:nobody *
#*代表jsproxy文件夹

**Comment by chen19870509** [comment]
![image](https://user-images.githubusercontent.com/23387662/59829555-48e38000-9370-11e9-82d5-07dc197eb8a6.png)

**Comment by chen19870509** [comment]
要在root权限下配置.....

**Comment by EtherDream** [comment]
地址栏后面加上 `/index.html` 试试？

**Comment by EtherDream** [comment]
我找到原因了，之前 `index.html` 移动导致的。需要在 `www.conf` 里加上：

```conf
location = / {
  rewrite             ^ /404.html;
}
```

等会我更新下。

**Comment by kejicheng** [comment]
/index.html 是这个问题，可以了。

**Comment by EtherDream** [comment]
> /index.html 是这个问题，可以了。

正常不用加 /index.html 的，修复了
