### ISSUE TITLE
最后运行run.sh有问题

### ISSUE THREAD

**Issue by lininn** [EtherDream/jsproxy#8]
nginx: [alert] could not open error log file: open() "/soft/proxy/server/nginx/logs/error.log" failed (2: No such file or directory)
2019/03/08 00:50:29 [emerg] 34282#0: mkdir() "/soft/proxy/server/nginx/cache" failed (2: No such file or directory)

**Comment by EtherDream** [comment]
server 目录下创建一个 nginx 目录试试？

**Comment by lininn** [comment]
运行成功无法访问？

**Comment by EtherDream** [comment]
本来有个 server/nginx 目录的，被 git 忽略了。不知 nginx 会不会自动创建这个目录。你手动补上试试。

**Comment by lininn** [comment]
本机的nginx需要指向nginx.conf?

**Comment by lininn** [comment]
运行成功却无法访问

**Comment by EtherDream** [comment]
> 本机的nginx需要指向nginx.conf?

run.sh 里面已经传入 nginx.conf 路径参数了。你运行 run.sh reload 试试？

**Comment by whtiehack** [comment]
需要手动创建这个目录的 `/soft/proxy/server/nginx/logs/` 不然会报错。

**Comment by EtherDream** [comment]
> 需要手动创建这个目录的 `/soft/proxy/server/nginx/logs/` 不然会报错。

我 git 里加上这个目录。

**Comment by whtiehack** [comment]
放个 .gitkeep就行了吧

**Comment by EtherDream** [comment]
> 放个 .gitkeep就行了吧

已加

**Comment by lininn** [comment]
表示自建目录也失败…创建了-------- 原始邮件 --------主题：Re: [EtherDream/jsproxy] 最后运行run.sh有问题 (#8)发件人：EtherDream 收件人：EtherDream/jsproxy 抄送：lininn ,Author 

放个 .gitkeep就行了吧



已加
