### ISSUE TITLE
一点意见

### ISSUE THREAD

**Issue by xieccc** [EtherDream/jsproxy#80]
感觉项目安装之后，就会在某一台公用服务器有记录ip。打开的html实际上是公用服务器从个人服务器拉的。这样做不是很好啊。
我看内置了nginx，直接用个人服务器的nginx配置应该可以更好一点，摆脱了必须要有一个公共服务器的问题，而且这样的服务更好的私人定制

**Comment by EtherDream** [comment]
安装之后默认是不需要公用服务器的，直接访问 `https://服务器IP.xip.io:8443` 就可以了。静态资源如果不想用默认那个 CDN 加速的话，可以修改 www/conf.js 的 CDN 地址为相对路径（那个注释打开就可以）

**Comment by xieccc** [comment]
请问项目的nginx配置在哪。。。根据提示是8443端口访问。但是我找了所有的conf都没有监听这个端口的配置

**Comment by EtherDream** [comment]
8443 端口是安装脚本生成的，在 cert/cert.conf 里，安装前文件是空的。

**Comment by chen19870509** [comment]
非root用户不要使用1024以下的端口
权限不够

**Comment by xieccc** [comment]
配置了一上午，cf -> 本机原先支持的nginx -> 项目附带nginx ->美化页面 ->完成
感谢EtherDream的奇思妙想与做出的项目。
同时能否推出不携带nginx，只携带nginx配置的项目，这样的话可以直接在原有nginx的基础上引入配置文件即可。。毕竟一个主机跑几个nginx有点怪

**Comment by EtherDream** [comment]
> 配置了一上午，cf -> 本机原先支持的nginx -> 项目附带nginx ->美化页面 ->完成
> 感谢EtherDream的奇思妙想与做出的项目。
> 同时能否推出不携带nginx，只携带nginx配置的项目，这样的话可以直接在原有nginx的基础上引入配置文件即可。。毕竟一个主机跑几个nginx有点怪

这个配置是基于 OpenResty 最新版的，有些指令或者 lua 模块在老的 nginx 上可能不支持。携带具体程序更方便一点，体积也才几十 MB 而已。

**Comment by xieccc** [comment]
好的吧，必须要依赖这个啊，怪不得用新的账号去做这种操作

**Comment by EtherDream** [comment]
> 好的吧，必须要依赖这个啊，怪不得用新的账号去做这种操作

新的账号并不完全因为单独的 nginx 程序，主要是降低权限，还有针对用户的 iptables 策略。
