### ISSUE TITLE
如何替换端口

### ISSUE THREAD

**Issue by chengqianliu** [EtherDream/jsproxy#86]
如何把8443端口换成别的端口改cert.conf那里的端口却没有权限执行

**Comment by EtherDream** [comment]
port < 1024 ?

**Comment by chengqianliu** [comment]
yes------------------ 原始邮件 ------------------
发件人: "EtherDream"<notifications@github.com>
发送时间: 2019年6月29日(星期六) 上午10:29
收件人: "EtherDream/jsproxy"<jsproxy@noreply.github.com>;
抄送: "chengqianliu"<1292978740@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EtherDream/jsproxy] 如何替换端口 (#86)



port < 1024 ?
 
&mdash;

**Comment by EtherDream** [comment]
```bash
setcap cap_net_bind_service=+eip /home/jsproxy/openresty/nginx/sbin/nginx
```

or

```bash
iptables -t nat -p tcp --dport 443 -j REDIRECT --to-ports 8443
```
