### ISSUE TITLE
你的服务器怎么了？

### ISSUE THREAD

**Issue by aydmn** [EtherDream/jsproxy#88]
`TypeError: Failed to fetch`

**Comment by Puled** [comment]
我也是。清缓存也没用，必须要隐身模式才能访问。
我按照教程在cloudflare上开了个免费账号，发现我不仅只能在隐身模式下才能访问（否则就failed to fetch），谷歌上不去（验证码点不了），而且太慢了，推特半分钟才打开，视频纯粹就看不了。实在是不懂电脑，完全看不懂代码，请问我这是为什么啊？

**Comment by EtherDream** [comment]
首页多刷新几次试试？

**Comment by lixshuang** [comment]
我觉得又不是付费的VPN，别人免费提供，提出问题的时候，态度至少好一点吧，连请问都忘记打？？？

**Comment by EtherDream** [comment]
> 我觉得又不是付费的VPN，别人免费提供，提出问题的时候，态度至少好一点吧，连请问都忘记打？？？

哈哈没事现在应该好了
