### ISSUE TITLE
谷歌搜索有异常

### ISSUE THREAD

**Issue by aydmn** [EtherDream/jsproxy#89]
点击”工具“，页面会跳转到[https://jsproxy.ga/-----https://www.google.com/null](https://jsproxy.ga/-----https://www.google.com/null)
![image](https://user-images.githubusercontent.com/41824047/60604331-09924600-9dea-11e9-9035-d7304974dbee.png)
![image](https://user-images.githubusercontent.com/41824047/60604410-321a4000-9dea-11e9-8ef6-cdaeaa30fcc1.png)

**Comment by EtherDream** [comment]
多谢反馈。已修复。

‪ʕ•ٹ•ʔ <notifications@github.com> 于2019年7月3日周三 下午11:28写道：‬
