### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by lininn** [EtherDream/jsproxy#9]
按照步骤执行，cloudflare失败，全部执行完毕，run.sh执行成功，无法访问

**Comment by EtherDream** [comment]
server/nginx/logs/warn.log 有错误日志吗？

**Comment by lininn** [comment]
./release.sh: line 2: brotli: command not found
/proxy/jsproxy/server/nginx/logs/nginx.pid" failed (2: No such file or directory)
有这个文件夹

**Comment by lininn** [comment]
觉得解决不了了，，，不能用

**Comment by whtiehack** [comment]
没问题的 我是部署成功的。#3

**Comment by lininn** [comment]
顺序执行，执行build.sh遇到./release.sh: line 2: brotli: command not found。

**Comment by whtiehack** [comment]
你是啥系统。项目作者用的 CentOS7，而我也是用的CentOS7，没有任何问题的。

**Comment by whtiehack** [comment]
另外我也用的是 cloudflare

**Comment by lininn** [comment]
能留个邮箱帮看下？

**Comment by EtherDream** [comment]
> ./release.sh: line 2: brotli: command not found
> /proxy/jsproxy/server/nginx/logs/nginx.pid" failed (2: No such file or directory)
> 有这个文件夹

你 git pull 下再试试，现在保留 server/nginx 目录了。

**Comment by lininn** [comment]
我也是centos7，按照步骤执行的

**Comment by whtiehack** [comment]
另外要在根目录执行 ./server/run.sh

**Comment by EtherDream** [comment]
> 另外要在根目录执行 ./server/run.sh

不在根目录应该也可以吧，里面按有考虑路径的

**Comment by whtiehack** [comment]
因为对linux不是非常熟悉，所以我是严格按照你的readme来执行的 。哈哈

**Comment by lininn** [comment]
build 中 brotli: command not found，rekease.sh中的brotli -f -o ../../server/www/x.js.br dist/main.js的brotli命令没找到

**Comment by EtherDream** [comment]
> build 中 brotli: command not found，rekease.sh中的brotli -f -o ../../server/www/x.js.br dist/main.js的brotli命令没找到

参考 server/setup.sh 里的安装命令

**Comment by lininn** [comment]
centos7完全放根目录？否则不报错也无法使用
