### ISSUE TITLE
大佬们，能请求出一个详细点的教程么

### ISSUE THREAD

**Issue by firesky123** [EtherDream/jsproxy#92]
作为一个萌新，只会把那个自动安装的命令复制粘贴，然后他就自动安好了，就没有然后了。但是自动安装的域名是自己服务器IP，而且线路那里还有两个演示站的地址，点了不能用。
  自己会用宝塔建静态，然后尝试去修改这个自动安装的东西，然后发现一脸懵逼，所以大佬们要是有时间的话，萌新恳请大佬们出一个详细一些的教程，然后萌新也可以学习一下里面的知识，在此谢谢各位大佬。

**Comment by breakwa2333** [comment]
这个东西不是用做违法用途的，如有需求左转v2ray

**Comment by firesky123** [comment]
> 这个东西不是用做违法用途的，如有需求左转v2ray

并不需要，ssr和v2ray都能搭，但是仅限于自己用。平时经常用到google scholar查文献然后导出endnote引文，自己用caddy搭建的scholar反代只能到搜索那一步，之后就不行了， 因为要跳转外链，看到这个项目后就想尝试用这个弄，但是自动脚本建立的站里面的东西都不会修改，如果要能自己改的话我只添加一个scholar就OK，然后自己用和课题组小范围用都OK。如果要用作违法用途我自己也慌得一批，毕竟服务器我自己出钱买的，只是在方便自己的同时又能方便一下身边的人，顺带学一点东西，本身专业与计算机无关，但是习惯捣鼓这个。

**Comment by EtherDream** [comment]
按照 https://github.com/EtherDream/jsproxy/blob/master/docs/setup.md 给自己的域名申请证书，然后修改下 nginx 配置就好了

**Comment by firesky123** [comment]
> 按照 https://github.com/EtherDream/jsproxy/blob/master/docs/setup.md 给自己的域名申请证书，然后修改下 nginx 配置就好了

emmm............这个手动安装的文档我之前也看了好几遍，但是这个nginx的配置文档。。。。说实话没看懂，脚本装好后我find一下nginx.conf，发现有两个，/home/jsproxy/openresty/nginx/conf/nginx.conf和/home/jsproxy/server/nginx.conf。但是我vi看了一下，没看明白个所以然，域名我有，申请ssl证书我也会，但是之前只看过Apache的文档，手动配置了网页就打不开了，然后就用宝塔部署了。。。。。
还有个问题想问一下大佬，项目里面的东西能修改吗，因为有很多类似推特啊之类的用不到，能不能隐藏或者怎么样。。。日常只用到scholar和最多用一下搜索

**Comment by EtherDream** [comment]
修改 /home/jsproxy/server/cert/cert.conf 里的证书路径

**Comment by firesky123** [comment]
> 修改 /home/jsproxy/server/cert/cert.conf 里的证书路径

谢谢大佬，刚试了下可以了，那端口号可以改吗，还是只能手动输入8443才可以，想实现直接输入网址就能打开

**Comment by EtherDream** [comment]
> > 修改 /home/jsproxy/server/cert/cert.conf 里的证书路径
> 
> 谢谢大佬，刚试了下可以了，那端口号可以改吗，还是只能手动输入8443才可以，想实现直接输入网址就能打开

最简单的办法就是把 443 转发到 8443。

```sh
iptables -t nat -p tcp --dport 443 -j REDIRECT --to-ports 8443
```

**Comment by firesky123** [comment]
谢谢大佬，前两天刚学会iptables转发端口，今天怎么没想到用于本地端口转发，好了，可以直接域名访问了，非常感谢！
